### PR TITLE
Support for fourth-level commands

### PR DESCRIPTION
**Pull request by danielbachhuber**
Will be dependent on https://github.com/wp-cli/wp-cli/pull/642

### CODE REVIEW

**Comment by joehoyle** [comment]
Nice!

**Comment by willmot** [comment]
Now that wp-cli/wp-cli#642 has landed I think this is good to merge?

**Comment by danielbachhuber** [comment]
It hasn't made it to a dot release yet

**Comment by 3flex** [comment]
https://github.com/wp-cli/wp-cli/pull/642 was replaced by https://github.com/wp-cli/wp-cli/pull/1005 which has been merged and is available in WP-CLI v0.15.0.

**Pull request closed without merging**
